# Generated by Django 5.0.6 on 2026-05-01 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('moisture', 'Moisture'), ('ph', 'Soil pH'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('npk', 'NPK')], max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('mqtt_topic', models.CharField(blank=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farms.plot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('npk_n', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('npk_p', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('npk_k', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.CharField(choices=[('mqtt', 'MQTT Sensor'), ('manual', 'Manual Entry'), ('simulator', 'Simulator')], default='mqtt', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='farms.plot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
