# Generated by Django 5.0.6 on 2026-05-01 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vision_scans/%Y/%m/%d/')),
                ('diagnosis', models.CharField(choices=[('healthy', 'Healthy'), ('early_blight', 'Early Blight'), ('late_blight', 'Late Blight'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recommendation', models.TextField()),
                ('model_version', models.CharField(default='mock_v1', max_length=50)),
                ('fed_to_engine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_scans', to='farms.plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
