# Generated by Django 5.0.6 on 2026-05-01 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('iot', '0001_initial'),
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.IntegerField()),
                ('health_status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('healthy', 'Healthy')], max_length=20)),
                ('growth_stage', models.CharField(blank=True, max_length=20)),
                ('xgboost_prediction', models.CharField(blank=True, max_length=50)),
                ('xgboost_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rule_triggered', models.BooleanField(default=False)),
                ('rule_name', models.CharField(blank=True, max_length=100)),
                ('feature_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='farms.cropcycle')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='farms.plot')),
                ('sensor_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.sensorreading')),
                ('weather_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weatherdata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('category', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('disease', 'Disease'), ('pest', 'Pest'), ('harvest', 'Harvest'), ('weather', 'Weather'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_required', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='engine.engineanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
