# Generated by Django 5.0.6 on 2026-05-01 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_current', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_probability_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_probability_48h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_mm_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frost_probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('raw_current', models.JSONField(blank=True, null=True)),
                ('raw_forecast', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='farms.farm')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
