# Generated by Django 5.2 on 2026-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='variety',
            field=models.CharField(blank=True, choices=[('shangi', 'Shangi'), ('dutch_robijn', 'Dutch Robijn'), ('markies', 'Markies'), ('kenya_mpya', 'Kenya Mpya'), ('tigoni', 'Tigoni'), ('other', 'Other')], max_length=50),
        ),
    ]
